# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'
steps:
- checkout: self

- script: |
    git clone https://008443260-Student@dev.azure.com/008443260-Student/Software_Engineering_Spring_2024_Project/_git/Fin-tastic_Division
    cd Fin-tastic_Division
    git config user.email "008458886@coyote.csusb.edu"
    git config user.name "008458886-VAMSI"
    git remote add github https://github.com/SE-Team-4-2024/Fin-tastic_Division.git
    git pull origin --all  # Fetch all branches from Azure Repo
    for branch in $(git branch -r | grep -v HEAD); do  # Iterate over all branches
        branch_name=$(echo $branch | sed 's/.*\///')  # Extract branch name
        git checkout -B $branch_name origin/$branch_name  # Checkout the branch
        git push github $branch_name  # Push the branch to GitHub
    done
  displayName: 'Sync Azure Repo to GitHub for all branches'
